name: Quizzes
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+10

environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^5.0.0
  http: ^0.13.5
  shared_preferences: ^2.0.17
  flutx: ^0.0.1
  font_awesome_flutter: ^10.3.0
  video_player: ^2.4.10
  animated_text_kit: ^4.2.2
  flutter_countdown_timer: ^4.1.0
  cached_network_image: ^3.2.1
  get: ^4.6.5
  assets_audio_player: ^3.0.6
  flutter_launcher_icons: ^0.11.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_icons:
  ios: true
  image_path: "assets/ic_launcher.png"


flutter:
  uses-material-design: true

  fonts:
    - family: Berlin
      fonts:
        - asset: fonts/berlin.ttf

    - family: FreigBold
      fonts:
        - asset: fonts/freigbold.otf
  
    - family: Freig
      fonts:
        - asset: fonts/freigmed.otf
  
  assets:
    - assets/
    - assets/audio/
    - assets/videos/